version: '3.8'

services:


  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: ecoair-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    volumes:
      - ./backend/app:/app/app
      - ./ml:/app/ml
    develop:
      watch:
        - action: sync+restart
          path: ./backend/app
          target: /app/app
        - action: sync+restart
          path: ./ml
          target: /app/ml
        - action: rebuild
          path: ./backend/requirements.txt

  frontend:
    build:
      context: ./frontend
    container_name: ecoair-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src
        - action: rebuild
          path: ./frontend/public
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/vite.config.js

